include $(GNUSTEP_MAKEFILES)/common.make

APP_NAME = MusicAppGNUstep

MusicAppGNUstep_HEADER_FILES = src/objc/AppDelegate.h src/objc/GuiController.h src/objc/Cst420Socket.h src/objc/UploadThread.h
MusicAppGNUstep_OBJC_FILES =  src/objc/AppDelegate.m src/objc/GuiController.m  src/objc/Cst420Socket.m src/objc/UploadThread.m src/objc/main.m

ADDITIONAL_OBJCFLAGS = -DWINGS
ADDITIONAL_CFLAGS = -DWINGS

include $(GNUSTEP_MAKEFILES)/application.make

